name: Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - "docs/"
    - "mkdocs.yml"
    - "README.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - "docs/"
    - "mkdocs.yml"
    - "README.md"

jobs:
  test:
    name: "Test & Coverage"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Set up hatch environment cache
      if: runner.os == 'Linux'
      uses: "actions/cache@v4"
      with:
        path: .venv/
        key: "hatch-env-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}"
        restore-keys: "hatch-env-${{ steps.setup-python.outputs.python-version }}-"
    - name: Install hatch
      run: pipx install hatch; hatch config set dirs.env.virtual ".venv"
    - name: Lint
      run: hatch run lint:all
    - name: Tests
      run: hatch run +py=${{ matrix.python-version }} all:test
